use crate::agent::adapter::ActorSessionMap;
use crate::agent::session_actor::ActorCommand;
use crate::models::RunMeta;
use crate::storage;
use std::time::Duration;
use tokio::sync::oneshot;
use tokio::time::timeout;

const TITLE_SYSTEM_PROMPT: &str =
    "You write short chat session titles. Reply with only the title text, nothing else.";

const MAX_PROMPT_CHARS: usize = 1200;
const MAX_TITLE_CHARS: usize = 48;
/// Outer timeout for the IPC `generate_run_title` round trip. The actor's
/// inner title task has a 25s internal timeout, so 30s gives the actor
/// task + IPC handoff some headroom.
const TITLE_IPC_TIMEOUT_SECS: u64 = 30;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum TitleGenPath {
    /// Actor mailbox path: title is generated by a task spawned from the
    /// session actor's own cmd_tx. The spawned process is tied to the
    /// actor's lifecycle via kill_on_drop.
    Actor,
    /// Legacy fallback: spawn a top-level `claude --print` from the IPC
    /// command handler. Used only when the actor for this run is not alive
    /// (e.g. user stopped the session before the title arrives).
    Direct,
}

/// Build the one-shot Claude prompt from the user's first message.
pub fn build_title_generation_prompt(user_prompt: &str) -> String {
    let trimmed = user_prompt.trim();
    let excerpt: String = trimmed.chars().take(MAX_PROMPT_CHARS).collect();
    format!(
        "Write a concise session title for this first user message.\n\
         Rules:\n\
         - Use the same language as the user message\n\
         - About 4-12 words, or about 8-24 Chinese characters\n\
         - No quotes, markdown, numbering, or trailing punctuation\n\
         - Name the concrete task; avoid generic titles like \"Question\" or \"Help\"\n\
         \n\
         User message:\n\
         {excerpt}"
    )
}

/// Normalize model output into a sidebar-safe title.
pub fn normalize_generated_title(raw: &str) -> String {
    let mut title = raw
        .lines()
        .find(|line| !line.trim().is_empty())
        .unwrap_or(raw)
        .trim()
        .trim_matches('"')
        .trim_matches('\'')
        .trim_matches('`')
        .trim()
        .to_string();

    for prefix in ["Title:", "标题:", "Session:", "会话:"] {
        if title.starts_with(prefix) {
            title = title[prefix.len()..].trim().to_string();
        }
    }

    if title.ends_with('.') || title.ends_with('。') {
        title.pop();
    }

    if title.chars().count() > MAX_TITLE_CHARS {
        title = title.chars().take(MAX_TITLE_CHARS).collect();
        title = title.trim_end().to_string();
        if !title.ends_with('…') {
            title.push('…');
        }
    }

    title
}

pub fn fallback_title_from_prompt(prompt: &str) -> String {
    let first_line = prompt.split('\n').next().unwrap_or("").trim();
    if first_line.is_empty() {
        return String::new();
    }
    normalize_generated_title(first_line)
}

pub fn is_usable_title(title: &str) -> bool {
    let trimmed = title.trim();
    trimmed.chars().count() >= 2 && trimmed.chars().count() <= MAX_TITLE_CHARS
}

pub fn should_generate_title(meta: &RunMeta) -> bool {
    if meta
        .name
        .as_ref()
        .is_some_and(|name| !name.trim().is_empty())
    {
        return false;
    }
    let prompt = meta.prompt.trim();
    !prompt.is_empty() && !prompt.starts_with('/')
}

/// Apply model output to produce the final title: normalize, validate, fall
/// back to the prompt excerpt if the model returned something unusable.
pub fn finalize_title(raw: &str, fallback: &str) -> String {
    let title = normalize_generated_title(raw);
    if is_usable_title(&title) {
        title
    } else {
        fallback.to_string()
    }
}

/// Generate a title for the given run, going through the session actor's
/// mailbox when possible. Falls back to a direct top-level `claude --print`
/// when the actor for this run is not alive (e.g. session was stopped
/// before the title arrived).
pub async fn generate_for_run(
    run_id: &str,
    sessions: Option<ActorSessionMap>,
) -> Result<String, String> {
    let meta = storage::runs::get_run(run_id).ok_or_else(|| format!("Run {run_id} not found"))?;

    if !should_generate_title(&meta) {
        if let Some(name) = meta.name.filter(|n| !n.trim().is_empty()) {
            return Ok(name);
        }
        return Err("Title generation not applicable".to_string());
    }

    let fallback = fallback_title_from_prompt(&meta.prompt);
    if meta.agent != "claude" {
        return Ok(fallback);
    }

    let generation_prompt = build_title_generation_prompt(&meta.prompt);
    let path = pick_path(sessions.as_ref(), run_id).await;
    let result = match path {
        TitleGenPath::Actor => {
            let sessions = sessions.expect("actor path requires a non-None session map");
            send_via_actor(run_id, generation_prompt, sessions).await
        }
        TitleGenPath::Direct => {
            // Direct legacy path: reserved for when the actor is gone. The
            // direct spawn is owned by this future — when the future is
            // dropped, the Child handle is dropped, which would normally
            // leak; we wrap with kill_on_drop(true) below to avoid that.
            log::warn!(
                "[title_generator] actor not found for run {run_id}, falling back to direct claude --print"
            );
            crate::commands::session::run_claude_print_prompt(&meta, generation_prompt, |adapter| {
                adapter.system_prompt = Some(TITLE_SYSTEM_PROMPT.to_string());
                adapter.append_system_prompt = None;
                adapter.max_turns = Some(1);
                adapter.permission_mode = Some("bypassPermissions".to_string());
            })
            .await
        }
    };

    match result {
        Ok(raw) => Ok(finalize_title(&raw, &fallback)),
        Err(err) => {
            log::warn!("[title_generator] Claude title failed for run {run_id}: {err}");
            Ok(fallback)
        }
    }
}

/// Heuristic: prefer the actor path when the session map has a live handle
/// for this run, otherwise fall back to a direct spawn.
async fn pick_path(sessions: Option<&ActorSessionMap>, run_id: &str) -> TitleGenPath {
    let Some(map) = sessions else {
        return TitleGenPath::Direct;
    };
    // tokio::sync::Mutex::lock() returns a future; await it briefly to peek.
    match timeout(Duration::from_millis(50), map.lock()).await {
        Ok(guard) => {
            if guard.contains_key(run_id) {
                TitleGenPath::Actor
            } else {
                TitleGenPath::Direct
            }
        }
        Err(_) => {
            // Lock contended — assume the actor is alive and let send_via_actor
            // either succeed or surface a clearer error.
            log::debug!(
                "[title_generator] session-map lock contended while routing run {run_id}; defaulting to actor path"
            );
            TitleGenPath::Actor
        }
    }
}

/// Send a `GenerateTitle` command to the actor and await the reply with a
/// 30-second outer timeout (the actor's inner title task has a 25-second
/// internal timeout, so 30s leaves headroom for the IPC round trip).
async fn send_via_actor(
    run_id: &str,
    generation_prompt: String,
    sessions: ActorSessionMap,
) -> Result<String, String> {
    let cmd_tx = {
        let guard = sessions.lock().await;
        guard
            .get(run_id)
            .ok_or_else(|| format!("Session for run {run_id} is not alive"))?
            .cmd_tx
            .clone()
    };

    let (reply_tx, reply_rx) = oneshot::channel();
    cmd_tx
        .try_send(ActorCommand::GenerateTitle {
            prompt: generation_prompt,
            reply: reply_tx,
        })
        .map_err(|e| format!("Failed to enqueue title-generation command: {e}"))?;

    match timeout(Duration::from_secs(TITLE_IPC_TIMEOUT_SECS), reply_rx).await {
        Ok(Ok(result)) => result,
        Ok(Err(_dropped)) => Err("Title-generation reply channel dropped".to_string()),
        Err(_elapsed) => Err("Title generation timed out (30s)".to_string()),
    }
}

/// Worker that runs on a tokio task spawned by the session actor when it
/// receives a `GenerateTitle` command. The spawned `claude --print` Child
/// is bound to this task — when the task is dropped (e.g. actor is dropped
/// on stop), the Child drops, and with `kill_on_drop(true)` the OS process
/// is killed. This keeps the title-gen process lifecycle tied to the
/// actor's lifecycle.
pub(crate) async fn spawn_title_for_run(
    run_id: &str,
    generation_prompt: &str,
    _sessions: ActorSessionMap,
) -> Result<String, String> {
    let meta = storage::runs::get_run(run_id).ok_or_else(|| format!("Run {run_id} not found"))?;
    crate::commands::session::run_claude_print_prompt(
        &meta,
        generation_prompt.to_string(),
        |adapter| {
            adapter.system_prompt = Some(TITLE_SYSTEM_PROMPT.to_string());
            adapter.append_system_prompt = None;
            adapter.max_turns = Some(1);
            adapter.permission_mode = Some("bypassPermissions".to_string());
        },
    )
    .await
    .map(|raw| {
        let fallback = fallback_title_from_prompt(&meta.prompt);
        finalize_title(&raw, &fallback)
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn normalize_strips_wrappers_and_truncates() {
        assert_eq!(
            normalize_generated_title("\"Fix login redirect bug\""),
            "Fix login redirect bug"
        );
        assert_eq!(
            normalize_generated_title("Title: 重构聊天页圆角"),
            "重构聊天页圆角"
        );
    }

    #[test]
    fn fallback_uses_first_line() {
        assert_eq!(
            fallback_title_from_prompt("Fix auth bug\nmore details"),
            "Fix auth bug"
        );
    }

    #[test]
    fn finalize_picks_normalized_when_usable() {
        assert_eq!(finalize_title("\"Fix bug\"", "fallback"), "Fix bug");
    }

    #[test]
    fn finalize_falls_back_when_unusable() {
        // Single character is below the 2-char minimum
        assert_eq!(
            finalize_title("x", "fallback from prompt"),
            "fallback from prompt"
        );
    }

    #[tokio::test]
    async fn pick_path_returns_direct_when_no_map() {
        // No session map provided (e.g. legacy call site): always direct.
        assert_eq!(pick_path(None, "run-1").await, TitleGenPath::Direct);
    }
}
